AWSTemplateFormatVersion: "2010-09-09"
Description: ALB path based routing

Resources:
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: AppLoadBalancer
      Subnets:
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: AppLoadBalancer

  AppLoadBalancerListener:
    Type: AWS::ElasticLoadBalancerV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  DefaultTargetGroup:
    Name: default
    VpcId: !Ref VPC
    Port: 80
    Protocol: HTTP

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: HelloWorldCluster